### PR TITLE
Fix: change maxBodyLength axios config to allow large inputs

### LINKED ISSUE #479: Exception thrown when passing large input to Orchestrator function
**Describe the bug**
I'm building a durable function in TypeScript. This function will take a big JSON file.

- Axios has a default size limit of 2 megabytes.
- This issue has been addressed once before in this issue: #93  where it was determined that azure limits requests to 100 megabytes, but only the maxContentLength was changed.
- maxContentLength is for the response, maxBodyLength is for the request ([documentation](https://axios-http.com/docs/req_config)).

Investigative information

Durable Functions extension version: [2.*, 3.0.0)
durable-functions npm module version: 2.1.1
Language (JavaScript/TypeScript) and version: 4.0.0
Node.js version: 16.19.0

If deployed to Azure App Service

Timeframe issue observed:
Function App name:
Function name(s):
Region:
Orchestration instance ID(s):
If you don't want to share your Function App name or Functions names on GitHub, please be sure to provide your Invocation ID, Timestamp, and Region - we can use this to look up your Function App/Function. Provide an invocation id per Function. See the [Functions Host wiki](https://github.com/Azure/azure-webjobs-sdk-script/wiki/Sharing-Your-Function-App-name-privately) for more details.

To Reproduce

Go to '...'
Click on '....'
Scroll down to '....'
See error
While not required, providing your orchestrator's source code in anonymized form is often very helpful when investigating unexpected orchestrator behavior.

Expected behavior

Actual behavior
A clear and concise description of what actually happened.

Screenshots

Known workarounds
Provide a description of any known workarounds you used.

Additional context

Development environment (ex. Visual Studio)
Links to source
Additional bindings used
Function invocation IDs

### PR DESCRIPTION
**Pull request by nials-relevant**
Closes #479

### CODE REVIEW

**Comment by davidmrdavid** [comment]
Thanks @nials-relevant for your contribution.
I'm a bit torn on accepting this change mostly because inputs and outputs to DF APIs are supposed to be relatively small, and therefore the default limit placed by axios makes for a convenient way of indirectly enforcing this on a DF client.

However, I also recognize that users who know what they are doing would benefit from this. Perhaps there's a middle ground where this setting can be configured, but we log a warning whenever large inputs over a given size are detected. Would something like that fit your usecase, @nials-relevant ?

File: src/durableorchestrationclient.ts [hunk 1]
```diff
@@ -158,6 +158,7 @@ export class DurableOrchestrationClient {
                 },
             },
             maxContentLength: Infinity,
+            maxBodyLength: 5000000,
```
Comment (davidmrdavid) [inline src/durableorchestrationclient.ts]: nit: please comment this section
``suggestion
            maxBodyLength: 5000000, // 5MB

```

**Review by davidmrdavid — COMMENTED** [review]
Just one nitpick prior to approval @nials-relevant

**Review by davidmrdavid — APPROVED** [review]
LGTM!

**Comment by davidmrdavid** [comment]
@hossam-nar: Can you please port this to V3?
